hankhng/scootify

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20200224181524_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
@JuliusLWCBC, created devise and user model. Can you review?
> added devise + user model created

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
@hankhng can u please review my friend?
> Home banner

- app/views/pages/home.html.erb
> btn primary changed

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
@kisiro55 Created the navbar. Please review, thanks.
> Home navbar

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
@hankhng hi my friend. just build a card and map layout. check it out and please merge it.
> Home cards

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
added home footer @thomasvanholder @JuliusLWCBC @kisiro55
> added footer

- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
@hankhng ive just edited the html and scss
> added the missing html for the footer and import

- app/controllers/fake_controller.rb
- app/views/fake/page1.html.erb
- app/views/fake/page2.html.erb
- app/views/fake/page3.html.erb
- app/views/fake/page4.html.erb
- config/routes.rb
- test/controllers/fake_controller_test.rb
i[ve created  a fake controller with pages to start playing around
> fakecontrollertoplayaround

- app/javascript/components/banner.js
- app/javascript/packs/application.js
- app/views/pages/home.html.erb
- package.json
- yarn.lock
@hankhng js text dynamics done.
> jsdynamicdone

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- app/views/shared/_navbar.html.erb
Hey thomas. would you like to review the basic linkes created on navbar for sign up, signin and logout? Its still basic and focused on functionallity. We could then work on next steps suchs as: 
- make it nicer
- define whether we want or not the license_type as presence:true (i would rather leave it like an optional field to fill so as not to overwhelm the user in the sign up form
:thanks
> Addlink navbar

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
Also added "license_type" to sign up. we might want to validate presence false this field on validation
next steps: 
- to make it nicer
-  link it to navbar
@ please check it up and merge on master.
> added signup and signin.still not linked to the navbar. 

- app/controllers/bookings_controller.rb
- test/controllers/bookings_controller_test.rb
- yarn.lock
incl methods:
index, new, create, show
methods still need to be modified for usability
> created Bookings controller: index, new, create, show

- app/assets/stylesheets/components/_alert.scss
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- app/views/shared/_navbar.html.erb
improved messages for login and out...still room for improvement but we could leave it for a second stage as its already functional.
> Nicermessageslogin

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/scooters_controller.rb
- app/policies/application_policy.rb
- app/policies/scooter_policy.rb
- db/migrate/20200225164818_add_admin_to_users.rb
- db/schema.rb
- test/policies/scooter_policy_test.rb
ive added pundit basic configuration. 
Please note: if you get not to the pages you might get go and change the policy for application or the model policy
> added basic pundit conbfiguration

- Gemfile
- Gemfile.lock
- app/views/bookings/index.html.erb
- db/seeds.rb
new price calculation
please check and add @kisiro55 @thomasvanholder @hankhng
> Scooter show

- app/views/bookings/_form.html.erb
- config/routes.rb
- db/migrate/20200225202538_add_date_to_booking2.rb
- db/schema.rb
> removed date: string and added start_date and end_date

- app/assets/stylesheets/components/_card.scss
- app/controllers/scooters_controller.rb
- app/policies/scooter_policy.rb
- app/views/scooters/index.html.erb
- app/views/scooters/owned.html.erb
- config/routes.rb
owned scooter page + route update + CSS
> owned scooter page + route update

- app/views/scooters/owned.html.erb
> added EDIT button on My Scooters page

- app/controllers/scooters_controller.rb
- app/views/scooters/_form.html.erb
- app/views/scooters/new.html.erb
- config/routes.rb
@kisiro55 fixing post for new scooter... that I broke lol.
> removed index root

- app/policies/booking_policy.rb
- app/views/bookings/index.html.erb
- app/views/scooters/owned.html.erb
- app/views/shared/_navbar.html.erb
> Filer owner

- app/controllers/scooters_controller.rb
i changed some code on index to show first manually created scooters and then the seeds
> make the new created cards come first, and then the seeds

- .gitignore
- app/views/scooters/show.html.erb
@hankhng @kisiro55 @thomasvanholder 
plesase merge
> Wednesd branch

- app/assets/stylesheets/components/_card.scss
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/shared/_navbar.html.erb
> Confirmation page

- app/views/scooters/owned.html.erb
- app/views/scooters/show.html.erb
> photos changing on scotter show (after creation) 

- app/views/scooters/show.html.erb
> bug fix - scooter show page

- app/assets/javascripts/application.js
- app/assets/stylesheets/pages/_show.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/scooters/show.html.erb
- app/views/shared/_navbar.html.erb
@hankhng @kisiro55 @thomasvanholder 
sticky navbar and nicer UI for loin and sign up
> Show page map

- app/controllers/pages_controller.rb
- app/controllers/scooters_controller.rb
- app/policies/application_policy.rb
- app/policies/scooter_policy.rb
- app/views/scooters/show.html.erb
changes on devise to allow access to login page.
> Homepageaccesible

- app/assets/stylesheets/pages/_show.scss
- app/controllers/scooters_controller.rb
- app/views/scooters/show.html.erb
@hankhng please check and merge thxx
> Thursday branch

- app/assets/stylesheets/components/_alert.scss
- app/controllers/scooters_controller.rb
- app/models/scooter.rb
- app/policies/booking_policy.rb
- app/policies/scooter_policy.rb
- app/views/scooters/owned.html.erb
i added some logic on the delete scooter. if it has bookings you cannot delete it.!
> adddeletelogiconscooter

- app/views/scooters/show.html.erb
- db/seeds.rb
> reviews added on show page view

- app/javascript/components/banner.js
- app/javascript/components/price_calculator.js
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/models/booking.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
FINALLY done with price calculator & date picker
> Restyling bookings/new

- app/views/scooters/_mapbox.html.erb
- app/views/scooters/index.html.erb
- app/views/shared/_footer.html.erb
Fixed map on home/ index page @thomasvanholder
> fixed map position

- app/assets/stylesheets/pages/_home.scss
- app/controllers/scooters_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/javascript/plugins/init_mapbox.js
- app/views/layouts/application.html.erb
- app/views/scooters/index.html.erb
- package.json
- yarn.lock
Algolia Implementation + Dynamics
> search by location

- db/seeds.rb
Photos are  seeded ramdomly but now they are fixed once created (before it was refreshing every time)
> changed photo seeds

- app/views/scooters/index.html.erb
changed the text on notfound location
> Notfoundlocationindex

- app/assets/stylesheets/components/_card.scss
- app/controllers/reviews_controller.rb
- app/policies/review_policy.rb
- app/views/bookings/index.html.erb
- app/views/reviews/_form.html.erb
- app/views/reviews/new.html.erb
- app/views/scooters/owned.html.erb
> Create bookings 

- app/views/scooters/owned.html.erb
> Bug fix: edit & delete button on my scooters page

- app/assets/stylesheets/components/_index.scss
- app/controllers/bookings_controller.rb
- app/javascript/plugins/flatpickr.js
- app/views/bookings/_form.html.erb
- app/views/bookings/show.html.erb
Bookings confirmation map fix & total price calculate
> Bookings confirmation map fix & total price calculate

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_mapbox.scss
- app/controllers/scooters_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/scooters/_info_window.html.erb
Marker pop up completed. Still working on custom marker.
> Marker pop up

- app/assets/stylesheets/components/_card.scss
- app/views/scooters/index.html.erb
- Added scale effect on prod card
> (/scooters/index): Scaling of cards on hover

- app/views/bookings/earnings.html.erb
- app/views/layouts/application.html.erb
> Bugfix tabname + earnings amount format 

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_home.scss
Spaced front page cards and got rid of border
> Spaced front page cards and got rid of border

- app/views/scooters/_form.html.erb
- app/views/scooters/edit.html.erb
> Edit scooter: button color change + back button

- app/assets/stylesheets/components/_mapbox.scss
- app/views/scooters/_info_window.html.erb
> Infomap styling
